product_matrix_by_vector is outside SparseMatrix class since inside it will call: void get_element_in_line( index_t i, index_t e, T& value ) const {     ringmesh_assert_not_reached; }
type light is precised for const SparseMatrix< T, light >& mat1,
param because without light or heavy it does not compile
on Windows, error C2770.